---
- hosts: mywebserver
  become: yes
  remote_user: ubuntu
  gather_facts: no
  
  tasks:
      - name: 'updates'
        raw: sudo apt-get update
      - name: Nginx setup
        become: yes
        apt: pkg=nginx state=installed update_cache=true
      - name: index.html copy
        template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
